config/routes.rb
Rails.application.routes.draw do
  resources :items do 
    get :upvote, on: :member
    
    
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :price, numericality: {greater_than: 0, allow_nil: true }
	
	validates :description, presence: true

	after_initialize {puts "init OK"} #Item.new; Item.first
	after_save {puts "saved"} #Item.save; Item.create; Item.update_attributes()
	after_create {puts "have been created"} 
	after_update {puts "update complete"}
	after_destroy {puts "deleted"} #Item.destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_filter :find_item, only: [:show, :edit, :update, :destroy, :upvote]

	def index
		@items = Item.all
		#render text: @items.map { |i|  "#{i.name}: #{i.price}" }.join.("<br/>")
		#render({ text: (@items.map { |i| "#{i.name}: #{i.price}: #{i.description}: #{i.id}" }.join("<br>")) })
		render "items/index"
	end



	# /items/1(или любой другой id) - GET
	def show 
		unless @item 

		render text: "page not found", status: 404
		end
	end


	# /items/new - GET
	def new
		@item = Item.new
	end


	#/items/1/edit - GET


	# /items - POST (данные не видны в строке)
	def create
		#@item = Item.create (name: params[:name], price: params[:price], real: params[:real], weight: params[:weight], description: params[:description])
		#render text: params.inspect #{}"#{@item.id}: #{@item.name} (#{!@item.new_record?})"
		

		@item = Item.create(items_params)

		if @item.errors.empty?
			#render "show"
			redirect_to item_path(@item) #items/:id вновь созданного товара
		else
			render "new"
		end
 
	end

	


	def edit
		
	end

	# /items/1 PUT
	def update
		 #ключ хэша для того чтобы найти в базе данных
		@item.update (params [:item])
		if @item.errors.empty?
			redirect_to redirect_to item_path(@item)
		else
			render "edit"
		end
	end


	# /items/1 DELETE 
	def destroy
		
		@item.destroy
		redirect_to action: "index"
	end

	def upvote
		@item.increment!(params[:votes_counter])
		redirect_to action: :index
	end

private
		def items_params
			params.require(:item).permit(:name, :price, :description, :real, :weight)
		end

		def find_item
			@item = Item.find(params[:id])
		end

		

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>editing  item</h1>

<%= form_for @item do |f| %>

	<p>Название:<br/><%= f.text_field :name %></p>
	<p>Цена:<br/><%= f.text_field :price %></p>
	<p>Описание:<br/><%= f.text_field :description %></p>
	<p>Вес:<br/><%= f.text_field :weight %></p>

	<p><%= f.submit "edit goods" %></p>

<% end %>

app/views/items/index.html.erb
<% @items.each do |i| %>
	<p><%= i.id %> <%= link_to i.name, item_path(i) %> :<%= i.price %></p>
	<p> :<%= link_to "delete!", i, method: :delete, data:{confirm: "are you sure?.."} %></p>
	<p>RATE:  <%= link_to "+", upvote_item_path(i) %></p>

<% end %>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= form_for @item do |f| %>
	<p>Цена:<br/><%= f.text_field :price %></p>
	<p>Название:<br/><%= f.text_field :name %></p>
	<p>Описание:<br/><%= f.text_field :description %></p>
	<p>Вес:<br/><%= f.text_field :weight %></p>

	<p><%= f.submit "create goods" %></p>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<ul>
	<li><%= @item.price %> usd</li>
	<li><%= @item.description %></li>
	<li> weight: <%= @item.weight %> kg</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>